# Generated by Django 5.2.8 on 2025-11-23 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(max_length=10, unique=True)),
                ('lantai', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('KOSONG', 'Kosong'), ('ISI', 'Terisi'), ('MAINTENANCE', 'Perbaikan')], default='KOSONG', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipeKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tipe', models.CharField(max_length=100, unique=True)),
                ('harga_per_bulan', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fasilitas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penyewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('ktp_foto', models.ImageField(blank=True, null=True, upload_to='ktp_penyewa/')),
                ('tanggal_masuk', models.DateField(default=django.utils.timezone.now)),
                ('durasi_sewa_bulan', models.PositiveIntegerField(default=1)),
                ('kamar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyewa', to='kost.kamar')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('keterangan', models.TextField(blank=True, help_text='Contoh: Bayar Kost Maret 2025')),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_bayar', to='kost.penyewa')),
            ],
        ),
        migrations.AddField(
            model_name='kamar',
            name='tipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kamar_list', to='kost.tipekamar'),
        ),
    ]
