# Generated by Django 5.2.8 on 2025-11-23 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewa',
            name='durasi_sewa_bulan',
            field=models.PositiveIntegerField(default=1, help_text='Berapa bulan sewa di awal'),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='nomor_hp',
            field=models.CharField(help_text='Nomor WA aktif', max_length=20),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='tanggal_masuk',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
